-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 23:21:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema klinikdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `klinikdb` ;

-- -----------------------------------------------------
-- Schema klinikdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `klinikdb` DEFAULT CHARACTER SET utf8 ;
USE `klinikdb` ;

-- -----------------------------------------------------
-- Table `klinikdb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`admin` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`admin` (
  `USERADMIN` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`USERADMIN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`answers` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`answers` (
  `IDANSWER` INT(11) NOT NULL,
  `ANSWER` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IDANSWER`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`branch` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`branch` (
  `IDBRANCH` VARCHAR(10) NOT NULL,
  `ALAMAT` CHAR(10) NULL DEFAULT NULL,
  `NAMABRANCH` VARCHAR(45) NULL DEFAULT NULL,
  `ISACTIVE` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`IDBRANCH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`nutritionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`nutritionist` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`nutritionist` (
  `USERNUTRITIONIST` VARCHAR(50) NOT NULL,
  `IDBRANCH` VARCHAR(10) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(50) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `FULLNAME` VARCHAR(50) NULL DEFAULT NULL,
  `ISACTIVE` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`USERNUTRITIONIST`),
  UNIQUE INDEX `email_UNQ` (`EMAIL` ASC),
  INDEX `FK_REFERENCE_11` (`IDBRANCH` ASC),
  CONSTRAINT `FK_REFERENCE_11`
    FOREIGN KEY (`IDBRANCH`)
    REFERENCES `klinikdb`.`branch` (`IDBRANCH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`patient` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`patient` (
  `USERPATIENT` VARCHAR(50) NOT NULL,
  `USERNUTRITIONIST` VARCHAR(50) NULL DEFAULT NULL,
  `IDBRANCH` VARCHAR(10) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(50) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `FULLNAME` VARCHAR(50) NULL DEFAULT NULL,
  `WEIGHT` INT(11) NULL DEFAULT NULL,
  `HEIGHT` INT(11) NULL DEFAULT NULL,
  `ISACTIVE` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`USERPATIENT`),
  UNIQUE INDEX `email_UNQP` (`EMAIL` ASC),
  INDEX `FK_REFERENCE_1` (`USERNUTRITIONIST` ASC),
  INDEX `FK_REFERENCE_12` (`IDBRANCH` ASC),
  CONSTRAINT `FK_REFERENCE_1`
    FOREIGN KEY (`USERNUTRITIONIST`)
    REFERENCES `klinikdb`.`nutritionist` (`USERNUTRITIONIST`),
  CONSTRAINT `FK_REFERENCE_12`
    FOREIGN KEY (`IDBRANCH`)
    REFERENCES `klinikdb`.`branch` (`IDBRANCH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`appointment` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`appointment` (
  `IDAPPOINTMENT` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNUTRITIONIST` VARCHAR(50) NULL DEFAULT NULL,
  `USERPATIENT` VARCHAR(50) NULL DEFAULT NULL,
  `DATEAPPOINTMENT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `APPROVEDBY` VARCHAR(50) NULL DEFAULT NULL,
  `APPROVED` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IDAPPOINTMENT`),
  INDEX `FK_REFERENCE_5` (`USERNUTRITIONIST` ASC),
  INDEX `FK_REFERENCE_6` (`USERPATIENT` ASC),
  CONSTRAINT `FK_REFERENCE_5`
    FOREIGN KEY (`USERNUTRITIONIST`)
    REFERENCES `klinikdb`.`nutritionist` (`USERNUTRITIONIST`),
  CONSTRAINT `FK_REFERENCE_6`
    FOREIGN KEY (`USERPATIENT`)
    REFERENCES `klinikdb`.`patient` (`USERPATIENT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`caloriesbible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`caloriesbible` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`caloriesbible` (
  `IDCAL` INT(4) NOT NULL AUTO_INCREMENT,
  `FOODNAME` VARCHAR(50) NULL DEFAULT NULL,
  `CALORIE` FLOAT(6,2) NULL DEFAULT NULL,
  `PROTEIN` FLOAT(5,2) NULL DEFAULT NULL,
  `FATS` FLOAT(4,2) NULL DEFAULT NULL,
  `CARBHDRT` FLOAT(5,2) NULL DEFAULT NULL,
  `CALCIUM` FLOAT(6,2) NULL DEFAULT NULL,
  `PHOSPHOR` FLOAT(6,2) NULL DEFAULT NULL,
  `IRON` FLOAT(5,2) NULL DEFAULT NULL,
  `VITA` FLOAT(7,2) NULL DEFAULT NULL,
  `VITB1` FLOAT(6,2) NULL DEFAULT NULL,
  `VITC` FLOAT(4,2) NULL DEFAULT NULL,
  `amount` FLOAT(4,1) NULL DEFAULT NULL,
  `FWEIGHT` INT(3) NULL DEFAULT NULL,
  `added` VARCHAR(10) NULL DEFAULT NULL,
  `ISACTIVE` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`IDCAL`))
ENGINE = InnoDB
AUTO_INCREMENT = 977
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `klinikdb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`chat` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`chat` (
  `IDCHAT` INT(11) NOT NULL AUTO_INCREMENT,
  `SENDER_ID` VARCHAR(50) NULL DEFAULT NULL,
  `RECEIVER_ID` VARCHAR(50) NULL DEFAULT NULL,
  `DATESENDING` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DATERECEIVER` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MESSAGE` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDCHAT`),
  INDEX `FK_REFERENCE_3` (`SENDER_ID` ASC),
  INDEX `FK_REFERENCE_4` (`RECEIVER_ID` ASC),
  CONSTRAINT `FK_REFERENCE_3`
    FOREIGN KEY (`SENDER_ID`)
    REFERENCES `klinikdb`.`nutritionist` (`USERNUTRITIONIST`),
  CONSTRAINT `FK_REFERENCE_4`
    FOREIGN KEY (`RECEIVER_ID`)
    REFERENCES `klinikdb`.`patient` (`USERPATIENT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`question` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`question` (
  `QUESTIONID` INT(11) NOT NULL,
  `QUESTIONS` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`QUESTIONID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`correctanswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`correctanswers` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`correctanswers` (
  `IDANSWER` INT(11) NOT NULL,
  `QUESTIONID` INT(11) NOT NULL,
  `CALORIESNEED` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`IDANSWER`, `QUESTIONID`),
  INDEX `FK_REFERENCE_15` (`QUESTIONID` ASC),
  CONSTRAINT `FK_REFERENCE_13`
    FOREIGN KEY (`IDANSWER`)
    REFERENCES `klinikdb`.`answers` (`IDANSWER`),
  CONSTRAINT `FK_REFERENCE_15`
    FOREIGN KEY (`QUESTIONID`)
    REFERENCES `klinikdb`.`question` (`QUESTIONID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`mealplan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`mealplan` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`mealplan` (
  `IDMEALPLAN_` INT(11) NOT NULL AUTO_INCREMENT,
  `CALORNEED` INT(11) NULL DEFAULT NULL,
  `FILES` LONGBLOB NULL DEFAULT NULL,
  `CREATEDBY` VARCHAR(50) NULL DEFAULT NULL,
  `FASE` INT(11) NULL DEFAULT NULL,
  `KDMP` CHAR(10) NULL DEFAULT NULL,
  `FILENAME` VARCHAR(70) NULL DEFAULT NULL,
  `TYPEFILE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDMEALPLAN_`),
  UNIQUE INDEX `KODEMEALPLAN_UNQ` (`KDMP` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`mealpick`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`mealpick` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`mealpick` (
  `IDPICK` INT(11) NOT NULL AUTO_INCREMENT,
  `USERPATIENT` VARCHAR(50) NULL DEFAULT NULL,
  `IDMEALPLAN_` INT(11) NULL DEFAULT NULL,
  `PICKEDBY` VARCHAR(50) NULL DEFAULT NULL,
  `DATEPICK` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDPICK`),
  INDEX `FK_REFERENCE_10` (`USERPATIENT` ASC),
  INDEX `FK_REFERENCE_18` (`IDMEALPLAN_` ASC),
  CONSTRAINT `FK_REFERENCE_10`
    FOREIGN KEY (`USERPATIENT`)
    REFERENCES `klinikdb`.`patient` (`USERPATIENT`),
  CONSTRAINT `FK_REFERENCE_18`
    FOREIGN KEY (`IDMEALPLAN_`)
    REFERENCES `klinikdb`.`mealplan` (`IDMEALPLAN_`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`membership` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`membership` (
  `IDmember` INT(11) NOT NULL AUTO_INCREMENT,
  `USERPATIENT` VARCHAR(50) NULL DEFAULT NULL,
  `DATEJOIN` DATE NULL DEFAULT NULL,
  `DATEEXPIRED` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IDmember`),
  INDEX `FK_REFERENCE_14` (`USERPATIENT` ASC),
  CONSTRAINT `FK_REFERENCE_14`
    FOREIGN KEY (`USERPATIENT`)
    REFERENCES `klinikdb`.`patient` (`USERPATIENT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`personalitytest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`personalitytest` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`personalitytest` (
  `IDPERTEST` INT(11) NOT NULL AUTO_INCREMENT,
  `USERPATIENT` VARCHAR(50) NULL DEFAULT NULL,
  `RESULT` VARCHAR(50) NULL DEFAULT NULL,
  `DATETEST` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IDPERTEST`),
  INDEX `FK_REFERENCE_2` (`USERPATIENT` ASC),
  CONSTRAINT `FK_REFERENCE_2`
    FOREIGN KEY (`USERPATIENT`)
    REFERENCES `klinikdb`.`patient` (`USERPATIENT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `klinikdb`.`useranswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `klinikdb`.`useranswers` ;

CREATE TABLE IF NOT EXISTS `klinikdb`.`useranswers` (
  `QUESTIONID` INT(11) NOT NULL,
  `USERPATIENT` VARCHAR(50) NOT NULL,
  `CHOOSENANSWERID` INT(11) NULL DEFAULT NULL,
  `DATETEST` DATE NULL DEFAULT NULL,
  `RESULTTEMP` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`QUESTIONID`, `USERPATIENT`),
  INDEX `FK_REFERENCE_16` (`USERPATIENT` ASC),
  CONSTRAINT `FK_REFERENCE_16`
    FOREIGN KEY (`USERPATIENT`)
    REFERENCES `klinikdb`.`patient` (`USERPATIENT`),
  CONSTRAINT `FK_REFERENCE_17`
    FOREIGN KEY (`QUESTIONID`)
    REFERENCES `klinikdb`.`question` (`QUESTIONID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
